# This workflow will build a .NET Framework project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment for .NET Framework

    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore dependencies
      run: nuget restore EmbedSender.sln
    - name: Build
      run: msbuild EmbedSender.sln /p:Configuration=Release
    - name: Test
      run: |
        # Run your tests if you have any
        # Example: vstest.console.exe path\to\your\test\project.dll
        echo "No tests specified in this example."
